# Generated by Django 2.2 on 2019-12-05 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='publishers', to='books_authors_app.Book'),
        ),
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.CharField(default='note', max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='desc_TEXT',
            field=models.TextField(null=True),
        ),
    ]
