# Generated by Django 2.2 on 2019-12-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DojoRead_app', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
        migrations.RemoveField(
            model_name='book',
            name='liked_users',
        ),
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default=3, max_length=55),
            preserve_default=False,
        ),
    ]
