# Generated by Django 2.2 on 2019-12-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock_in_out_app', '0002_auto_20191217_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clock',
            name='task_des',
            field=models.CharField(default='default_des', max_length=255),
        ),
    ]
