# Generated by Django 2.2 on 2019-12-17 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clock_in_out_app', '0003_auto_20191217_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clock',
            name='task_des',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='clock',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clocks', to='clock_in_out_app.User'),
        ),
    ]
