# Generated by Django 2.2 on 2019-12-17 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clock_in_out_app', '0004_auto_20191217_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clock',
            name='clockin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clock',
            name='clockout',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clock',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clocks', to='clock_in_out_app.User'),
        ),
    ]
