# Generated by Django 2.2 on 2019-12-18 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock_in_out_app', '0005_auto_20191217_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='clock',
            name='clock_hours',
            field=models.FloatField(default=0.0),
        ),
    ]
