# Generated by Django 2.2 on 2019-12-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock_in_out_app', '0006_clock_clock_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='clock',
            name='clock_points',
            field=models.FloatField(default=0.0),
        ),
    ]
