# Generated by Django 2.2 on 2019-12-19 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clock_in_out_app', '0007_clock_clock_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='clock_in_out_app.User')),
                ('clock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='clock_in_out_app.Clock')),
            ],
        ),
    ]
