# Generated by Django 2.2 on 2019-12-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock_in_out_app', '0008_award'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='onEdit',
            field=models.BooleanField(default=False),
        ),
    ]
