# Generated by Django 2.2 on 2019-12-20 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clock_in_out_app', '0009_quote_onedit'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_awards', to='clock_in_out_app.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='award',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_awards', to='clock_in_out_app.User'),
        ),
        migrations.AlterField(
            model_name='award',
            name='clock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clock_awards', to='clock_in_out_app.Clock'),
        ),
    ]
