# Generated by Django 2.2 on 2019-12-20 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clock_in_out_app', '0010_auto_20191220_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='admin',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='admin_awards', to='clock_in_out_app.User'),
        ),
        migrations.AlterField(
            model_name='award',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_awards', to='clock_in_out_app.User'),
        ),
    ]
