# Generated by Django 2.2 on 2019-12-20 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock_in_out_app', '0011_auto_20191220_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='reasons',
            field=models.CharField(default='some good default reason', max_length=255),
        ),
    ]
