# Generated by Django 2.2 on 2019-12-20 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clock_in_out_app', '0012_award_reasons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='clock',
        ),
    ]
