# Generated by Django 2.2 on 2019-12-20 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clock_in_out_app', '0013_remove_award_clock'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='clock',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='clock_awards', to='clock_in_out_app.Clock'),
        ),
    ]
