# Generated by Django 2.2 on 2019-12-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_table_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isAdmin',
        ),
        migrations.AddField(
            model_name='user',
            name='user_level',
            field=models.IntegerField(default=0),
        ),
    ]
