# Generated by Django 2.2 on 2019-12-13 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_table_app', '0002_auto_20191212_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(default='default description', max_length=255),
        ),
    ]
