# Generated by Django 2.2 on 2019-12-13 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_table_app', '0004_comment_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
    ]
